env:
  es2021: true
  node: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "import/extensions": [0, "never"],
  "no-console": "off",
  "no-underscore-dangle": "off"
}
